apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '11'
  generation: 21
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-test-amine-repo
  name: test-amine-repo
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-test-amine-repo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: amine
        workload.user.cattle.io/workloadselector: apps.deployment-default-test-amine-repo
    spec:
      affinity: {}
      containers:
        - image: damine2022/amine_repo:latest
          imagePullPolicy: Always
          name: container-0
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: amine-repo-sec2
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: amine-repo-srv
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: amine-repo-port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: amine
  sessionAffinity: None
  type: NodePort